### ISSUE TITLE
oxlongdesc is missing (database)

### ISSUE THREAD

**Issue by tabsl** [OXIDprojects/oxid-rest-api#2]
oxlongdesc is missing ArticleController::showAllArticles() and ArticleController::showOneArticle()

**Comment by wolf128058** [comment]
Perhaps "... FROM oxarticles LEFT OUTER JOIN oxartextends ON oxarticles.oxid = oxartextends.oxid WHERE ..." could do a little magic for this issue (ArticleControllerOxid.php, line 46)

**Comment by tabsl** [comment]
ups, another bug ... issued #5

**Comment by tabsl** [comment]
fixed with https://github.com/OXIDprojects/oxid-rest-api/commit/4d466e9372db3e7b34bdaf4331d6817eca93c208
