### ISSUE TITLE
Package 'mysql-client' has no installation candidate

### ISSUE THREAD

**Issue by Jenya222** [OXIDprojects/oxid-rest-api#8]
![image](https://user-images.githubusercontent.com/19821303/67148295-e57a4800-f2a6-11e9-99d5-dce981da4e8f.png)

During an installation causes an error that 

> Package 'mysql-client' has no installation candidate

It happens because this package doesn't exist in buster repository. Instead of this needs to use `default-mysql-client` package

**Comment by proudcommerce** [comment]
When it works, can you provide a PR? 
UPDATE: https://github.com/OXIDprojects/oxid-rest-api/pull/9 ;-)

**Comment by Jenya222** [comment]
@proudcommerce Hello! Yes i fixed it here :) https://github.com/OXIDprojects/oxid-rest-api/pull/9

**Comment by proudcommerce** [comment]
merged #9
